version: '2'
services:
  fly-admin:
    image: renren/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  fly-api:
    image: renren/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev